<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sfr</string>
	</array>
	<key>name</key>
	<string>Shaderforth</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?!\s)\((?=\s)</string>
			<key>comment</key>
			<string>comment</string>
			<key>end</key>
			<string>(?!\s)\)(?=\s)</string>
			<key>name</key>
			<string>comment.shaderforth</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>comment.shaderforth</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>(?!\s)#?-?+?([0-9]+|[0-9]+\.[0-9]*|\.[0-9]+)(?=\s)</string>
			<key>name</key>
			<string>constant.numeric.shaderforth</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?!\s)(:)\s+([^\s]+)\s+(\(\s+([^\)]+\s+)?\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.shaderforth</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.shaderforth</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.shaderforth</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>words</string>
			<key>end</key>
			<string>(?!\s);(?=\s)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.shaderforth</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.shaderforth</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.name.shaderforth</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>imports</string>
			<key>match</key>
			<string>(?!\s)import\[\s(.*?)\s\](?=\s)</string>
			<key>name</key>
			<string>keyword.import.shaderforth</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?!\s):m\s+([^\s]+)(\s+\(\s+([^\)]+\s+)?\))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.shaderforth</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.shaderforth</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.shaderforth</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>macros</string>
			<key>end</key>
			<string>(?!\s);(?=\s)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.shaderforth</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.shaderforth</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?!\s)(:globals|:passes)(?=\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.shaderforth</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>globals/passes</string>
			<key>end</key>
			<string>(?!\s);(?=\s)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.shaderforth</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.shaderforth</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?!\s)\[(?=\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.array.shaderforth</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>arrays</string>
			<key>end</key>
			<string>(?!\s)\][mv]?(?=\s)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.array.shaderforth</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.array.shaderforth</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?!\s)[\\/]?\{(\s+\(\s+([^\)]+\s+)?\))?(?=\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.block.shaderforth</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.shaderforth</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>blocks</string>
			<key>end</key>
			<string>(?!\s)\}(?=\s)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.block.shaderforth</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.shaderforth</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>operations</string>
			<key>match</key>
			<string>(?!\s)[\\/*/+-&lt;&gt;=~!@#$%^&amp;|?]+(?=\s)</string>
			<key>name</key>
			<string>keyword.shaderforth</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.shaderforth</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.name.shaderforth</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>named</string>
			<key>match</key>
			<string>(?!\s)(-&gt;|=&gt;|=|\.|&amp;|\\|/|\*|@)([a-zA-Z0-9\-_~!@#$%^&amp;*()\[\]+=+&lt;&gt;]+)(?=\s)</string>
			<key>name</key>
			<string>keyword.shaderforth</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.shaderforth</string>
	<key>uuid</key>
	<string>3f3a3f53-00ee-4b3f-afb8-78cdf3761a3b</string>
</dict>
</plist>
